INSERT INTO UTILISATEUR (ID_UTILISATEUR, UTI_LOGIN, UTI_PASSWORD, UTI_ENABLED) VALUES (1, 'admin', 'd033e22ae348aeb5660fc2140aec35850c4da997', true);
INSERT INTO UTILISATEUR (ID_UTILISATEUR, UTI_LOGIN, UTI_PASSWORD, UTI_ENABLED) VALUES (2, 'user', '12dea96fec20593566ab75692c9949596833adc9', true);
INSERT INTO UTILISATEUR (ID_UTILISATEUR, UTI_LOGIN, UTI_PASSWORD, UTI_ENABLED) VALUES (3, 'userdb', '62c76a220118c16919dc3b6beda5434c3987c1e9', true);

INSERT INTO ROLE (ID_ROLE, ROL_NOM) VALUES (1, 'APPLI_TUTO_ADMIN');
INSERT INTO ROLE (ID_ROLE, ROL_NOM) VALUES (2, 'APPLI_TUTO_USER');
INSERT INTO ROLE (ID_ROLE, ROL_NOM) VALUES (3, 'APPLI_TUTO_USER');
INSERT INTO ROLE (ID_ROLE, ROL_NOM) VALUES (4, 'APPLI_TUTO_USER');

INSERT INTO ROLE_UTILISATEUR (ID_UTILISATEUR, ID_ROLE) VALUES (1, 1);
INSERT INTO ROLE_UTILISATEUR (ID_UTILISATEUR, ID_ROLE) VALUES (1, 2);
INSERT INTO ROLE_UTILISATEUR (ID_UTILISATEUR, ID_ROLE) VALUES (2, 3);
INSERT INTO ROLE_UTILISATEUR (ID_UTILISATEUR, ID_ROLE) VALUES (3, 4);

INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (1, 'Lebon', 'Julien', 'M', 28, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (2, 'Trebern', 'Gilles', 'M', 66, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (3, 'Clam', 'Juliette', 'F', 28, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (4, 'Durant', 'Jacqueline', 'F', 58, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (5, 'Beat', 'Axel', 'M', 55, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (6, 'Beat', 'Axelle', 'F', 55, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (7, 'Lebrun', 'Adrien', 'M', 29, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (8, 'Dupont', 'Jack', 'M', 28, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (9, 'Doe', 'Jean', 'M', 28, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (10, 'Lenoir', 'Adeline', 'F', 28, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (11, 'Nouvelle', 'Sara', 'F', 28, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (12, 'Fages', 'Simon', 'M', 28, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (13, 'Larad', 'Alban', 'M', 28, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (14, 'Larad', 'Olivier', 'M', 38, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (15, 'Julien', 'Katrine', 'F', 28, '');
INSERT INTO PERSONNE (ID_PERSONNE, NOM,  PRENOM, SEXE, AGE,  DESC_PERS) VALUES (16, 'Julien', 'Christelle', 'F', 18, '');
COMMIT;